spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Fmc123
    url: jdbc:mysql://10.51.36.135:3306/eyas?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8&useUnicode=true

logging:
  level:
    root: warn
    com.maoda.mp: trace
  pattern:
    console: '%p%m%n'